# Generated by Django 4.0.6 on 2022-07-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_samplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleModel',
        ),
    ]
