# Generated by Django 4.0.6 on 2022-07-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
